### ISSUE TITLE
[Space], [']で前候補にもどれるようにする。

### ISSUE THREAD

**Issue by ShikiOkasaka** [esrille/ibus-hiragana#47]
[Space]のあとかな文字ならそのままシフト面の字の入力になる点に注意。

**Comment by MadeInWarioFan** [comment]
前候補を「[Space]→['] 」で行う方法は、NewStickneyや新JIS配列などのセンターシフトを持つ仮名配列でしか使えません。
ローマ字入力のばあい、[Space]を押した瞬間に変換が作動するため、左Shiftキーに[Shift]と[おくる]を兼務させる方法を提案しました。
左Shiftキーの次に押したキーが
仮名文字（センターシフトキーも同様）…[おくる]キーとして作動
仮名文字以外（変換、カタカナキー、空白、句読点など）…[Shift]キーとして作動
Twitterで述べたことに少し追加しました。

**Comment by MadeInWarioFan** [comment]
例「飛んで」
と 「と」
左Shift 「と」 （変化しない）
ん 「と＊ん」
で 「と＊んで」
変換 「飛んで」
変換 「富んで」
左Shift 「富んで」 （変化しない）
変換 「飛んで」（左Shift+変換で前候補）
送り仮名の印を＊としました。
※SKKでも送り仮名の頭文字を打たないと変換できないので、重大な欠陥にはならないと思います。

**Comment by ShikiOkasaka** [comment]
v0.12.0では対応ずみです。[いつから？]
