### ISSUE TITLE
半角カナ

### ISSUE THREAD

**Issue by nkyossi** [esrille/ibus-hiragana#68]
半角カタカナを簡単に入力できるとうれしいです。

**Comment by ShikiOkasaka** [comment]
イメージされている入力方法はありますか？
- 入力ずみのもじをあとから半角カタカナにかえていく
- はじめから半角カタカナで入力していく

など。

**Comment by nkyossi** [comment]
おそくなりすみません。
イメージは「はじめから」でしたが、どちらでも大丈夫です。

**Comment by ShikiOkasaka** [comment]
512d5cea4c9e3544efc5050727dd7b07a487cb98 で対応しました。
